### ISSUE TITLE
Name and logo

### ISSUE THREAD

**Issue by vivekprakash78** [vivekprakash78/Connect#10]
@harsh07bharvada  this is probably the biggest issue we have now.Look into it

**Comment by harsh07bharvada** [comment]
That is probably one of the things i can do now positively.

**Comment by vivekprakash78** [comment]
I think we connect with the name 'Connect' more, Let it be the name
If it's okay with everyone.
@harsh07bharvada @agarwal00s @Amiteshupadhyay
