### ISSUE TITLE
Upload img

### ISSUE THREAD

**Issue by vivekprakash78** [vivekprakash78/Connect#5]
Harsh please make necessary changes in uploadimg and user files to have image upload without reloading the page.

**Comment by harsh07bharvada** [comment]
okies. Onto it.

**Comment by vivekprakash78** [comment]
@harsh07bharvada  keep trying bro.. don't worry

**Comment by vivekprakash78** [comment]
@harsh07bharvada  not working correctly bro.

**Comment by vivekprakash78** [comment]
@harsh07bharvada if u need to refresh it, no use of ajax just post it and then use location( connect/home.php#profile)

**Comment by vivekprakash78** [comment]
@harsh07bharvada  i am closing this issue as i blv its done.
